# Include immediately after project(), before any target: one consistent inline
# definition for ALL consumers, including standalone/header-only test targets.
set(BC2_NATIVE_OPERATION_CAPABILITIES_HEADER "" CACHE FILEPATH "Private reviewed common operation receipts; default disabled")
set(BC2_NATIVE_OPERATION_SOURCE_RECEIPT "" CACHE FILEPATH "Exact nonrecursive operation source-set/header receipt")
set(BC2_NATIVE_OPERATION_SOURCE_SHA256 "" CACHE STRING "Reviewed operation source-set digest; default disabled")
if(BC2_NATIVE_OPERATION_CAPABILITIES_HEADER OR BC2_NATIVE_OPERATION_SOURCE_RECEIPT OR BC2_NATIVE_OPERATION_SOURCE_SHA256)
  if(NOT EXISTS "${BC2_NATIVE_OPERATION_CAPABILITIES_HEADER}" OR NOT EXISTS "${BC2_NATIVE_OPERATION_SOURCE_RECEIPT}")
    message(FATAL_ERROR "Native operation capability requires BOTH reviewed header and source receipt")
  endif()
  string(LENGTH "${BC2_NATIVE_OPERATION_SOURCE_SHA256}" _bc2_op_digest_length)
  if(NOT _bc2_op_digest_length EQUAL 64 OR NOT BC2_NATIVE_OPERATION_SOURCE_SHA256 MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Native operation source digest must be 64 lowercase hexadecimal characters")
  endif()
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  set(_bc2_op_verify "${CMAKE_SOURCE_DIR}/tools/bc2_native_operation_receipts.py" verify-source
    --root "${CMAKE_SOURCE_DIR}" --reviewed-header "${BC2_NATIVE_OPERATION_CAPABILITIES_HEADER}"
    --receipt "${BC2_NATIVE_OPERATION_SOURCE_RECEIPT}" --expected "${BC2_NATIVE_OPERATION_SOURCE_SHA256}")
  execute_process(COMMAND "${Python3_EXECUTABLE}" ${_bc2_op_verify} RESULT_VARIABLE _bc2_op_verified ERROR_VARIABLE _bc2_op_error OUTPUT_QUIET)
  if(NOT _bc2_op_verified EQUAL 0)
    message(FATAL_ERROR "Native operation provenance verification failed: ${_bc2_op_error}")
  endif()
  file(TO_CMAKE_PATH "${BC2_NATIVE_OPERATION_CAPABILITIES_HEADER}" _bc2_op_header)
  add_compile_definitions(FVR_BC2_NATIVE_OPERATION_CAPABILITIES_HEADER="${_bc2_op_header}"
    FVR_BC2_NATIVE_OPERATION_BUILD_SHA256="${BC2_NATIVE_OPERATION_SOURCE_SHA256}")
  add_custom_target(BC2NativeOperationSourceGuard ALL COMMAND "${Python3_EXECUTABLE}" ${_bc2_op_verify} VERBATIM)
  function(_bc2_attach_dir_operation_guard _bc2_directory)
    get_property(_bc2_targets DIRECTORY "${_bc2_directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(_bc2_target IN LISTS _bc2_targets)
      get_target_property(_bc2_type "${_bc2_target}" TYPE)
      if(NOT _bc2_target STREQUAL "BC2NativeOperationSourceGuard" AND NOT _bc2_type STREQUAL "INTERFACE_LIBRARY")
        add_dependencies("${_bc2_target}" BC2NativeOperationSourceGuard)
      endif()
    endforeach()
    get_property(_bc2_children DIRECTORY "${_bc2_directory}" PROPERTY SUBDIRECTORIES)
    foreach(_bc2_child IN LISTS _bc2_children)
      _bc2_attach_dir_operation_guard("${_bc2_child}")
    endforeach()
  endfunction()
  function(_bc2_attach_operation_guard)
    _bc2_attach_dir_operation_guard("${CMAKE_SOURCE_DIR}")
  endfunction()
  cmake_language(DEFER CALL _bc2_attach_operation_guard)
endif()
